version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      k8s.io:
        patterns:
        - "k8s.io/*"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      k8s.io:
        patterns:
        - "k8s.io/*"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    target-branch: release-1.31
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      k8s.io:
        patterns:
        - "k8s.io/*"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    target-branch: release-1.30
