{{- if or (not .Values.splitMode.enabled) (eq .Values.splitMode.type "workload") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleName }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRoleName }}
subjects:
{{- if and .Values.splitMode.enabled (eq .Values.splitMode.type "workload") }}
- kind: User
  name: {{ .Values.splitMode.subject.name }}
{{- else }}
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
{{- end }}
