apiVersion: v1
appVersion: "v1.19.0"
description: Cinder CSI Chart for OpenStack
name: openstack-cinder-csi
version: 1.2.1
home: https://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: brtknr
    email: brtknr@bath.edu
