apiVersion: v1
appVersion: v1.30.0
description: Cinder CSI Chart for OpenStack
name: openstack-cinder-csi
version: 2.30.1-alpha.1
home: https://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: mnasiadka
    email: mnasiadka@gmail.com
  - name: mkjpryor
    email: matt@stackhpc.com
