apiVersion: v1
appVersion: v1.21.0
description: Cinder CSI Chart for OpenStack
name: openstack-cinder-csi
version: 1.3.7
home: https://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: brtknr
    email: brtknr@bath.edu
