apiVersion: v1
appVersion: v1.24.6
description: Manila CSI Chart for OpenStack
name: openstack-manila-csi
version: 2.24.0
home: http://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: brtknr
    email: brtknr@bath.edu
