apiVersion: v1
appVersion: v1.34.0
description: Manila CSI Chart for OpenStack
name: openstack-manila-csi
version: 2.34.0
home: http://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: mnasiadka
    email: mnasiadka@gmail.com
  - name: mkjpryor
    email: matt@stackhpc.com
