apiVersion: v1
appVersion: v1.27.0-alpha.1
description: Manila CSI Chart for OpenStack
name: openstack-manila-csi
version: 2.27.0-alpha.1
home: http://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: brtknr
    email: brtknr@bath.edu
