# Base name of the CSI Manila driver
driverName: manila.csi.openstack.org

# Enabled Manila share protocols
shareProtocols:
  - protocolSelector: NFS
    fwdNodePluginEndpoint:
      dir: /var/lib/kubelet/plugins/csi-nfsplugin
      sockFile: csi.sock
#  - protocolSelector: CEPHFS
#    fwdNodePluginEndpoint:
#      dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
#      sockFile: csi.sock

# CSI Manila spec
csimanila:
  # Set topologyAwarenessEnabled to true to enable topology awareness
  topologyAwarenessEnabled: false
  # Runtime configuration
  runtimeConfig:
    enabled: false
    jsonData: |-
      {
        "nfs": {
          "matchExportLocationAddress": "172.168.122.0/24"
        }
      }
  # Availability zone for each node. topologyAwarenessEnabled must be set to true for this option to have any effect.
  # If your Kubernetes cluster runs atop of Nova and want to use Nova AZs as AZs for the nodes of the cluster, uncomment the line below:
  # nodeAZ: "$(curl http://169.254.169.254/openstack/latest/meta_data.json | jq -r .availability_zone)"
  # Image spec
  image:
    repository: k8scloudprovider/manila-csi-plugin
    tag: v1.19.0
    pullPolicy: IfNotPresent

# DeamonSet deployment
nodeplugin:
  # Component name
  name: nodeplugin
  # CSI Manila container compute resources constraints
  nodeplugin:
    resources: {}
  # csi-node-driver-registrar
  registrar:
    image:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.1.0
      pullPolicy: IfNotPresent
    resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Use fullnameOverride to fully override the name of this component
  # fullnameOverride: some-other-name

# StatefulSet deployment
controllerplugin:
  name: controllerplugin
  # CSI Manila container compute resources constraints
  nodeplugin:
    resources: {}
  # CSI external-provisioner container spec
  provisioner:
    image:
      repository: quay.io/k8scsi/csi-provisioner
      tag: v1.4.0
      pullPolicy: IfNotPresent
    resources: {}
  # CSI external-snapshotter container spec
  snapshotter:
    image:
      repository: quay.io/k8scsi/csi-snapshotter
      tag: v1.2.2
      pullPolicy: IfNotPresent
    resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Use fullnameOverride to fully override the name of this component
  # fullnameOverride: some-other-name

# Override the default app name using nameOverride
# nameOverride: some-other-name
