kind: Service
apiVersion: v1
metadata:
  name: openstack-manila-csi-controllerplugin
  labels:
    app: openstack-manila-csi
    component: controllerplugin
spec:
  selector:
    app: openstack-manila-csi
    component: controllerplugin
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: openstack-manila-csi-controllerplugin
  labels:
    app: openstack-manila-csi
    component: controllerplugin
spec:
  serviceName: openstack-manila-csi-controllerplugin
  replicas: 1
  selector:
    matchLabels:
      app: openstack-manila-csi
      component: controllerplugin
  template:
    metadata:
      labels:
        app: openstack-manila-csi
        component: controllerplugin
    spec:
      serviceAccountName: openstack-manila-csi-controllerplugin
      containers:
        - name: provisioner
          image: "registry.k8s.io/sig-storage/csi-provisioner:v5.3.0"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--extra-create-metadata"
            # To enable topology awareness in csi-provisioner, uncomment the following line:
            # - "--feature-gates=Topology=true"
          env:
            - name: ADDRESS
              value: "unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi-controllerplugin.sock"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/manila.csi.openstack.org
        - name: snapshotter
          image: "registry.k8s.io/sig-storage/csi-snapshotter:v8.3.0"
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: "unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi-controllerplugin.sock"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/manila.csi.openstack.org
        - name: resizer
          image: "registry.k8s.io/sig-storage/csi-resizer:v1.14.0"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: "unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi-controllerplugin.sock"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/manila.csi.openstack.org
        - name: nodeplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: registry.k8s.io/provider-os/manila-csi-plugin:v1.34.0
          command: ["/bin/sh", "-c",
            '/bin/manila-csi-plugin
            --endpoint=$(CSI_ENDPOINT)
            --drivername=$(DRIVER_NAME)
            --share-protocol-selector=$(MANILA_SHARE_PROTO)
            --fwdendpoint=$(FWD_CSI_ENDPOINT)
            --pvc-annotations'
            # To enable topology awareness and retrieve compute node AZs from the OpenStack Metadata Service, add the following flag:
            # --with-topology
            # This flag needs to be added to csi-nodeplugin.yaml as well.
          ]
          env:
            - name: DRIVER_NAME
              value: manila.csi.openstack.org
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: "unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi-controllerplugin.sock"
            - name: FWD_CSI_ENDPOINT
              value: "unix:///var/lib/kubelet/plugins/FWD-NODEPLUGIN/csi.sock"
            - name: MANILA_SHARE_PROTO
              value: "SHARE-PROTOCOL"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/manila.csi.openstack.org
            - name: fwd-plugin-dir
              mountPath: /var/lib/kubelet/plugins/FWD-NODEPLUGIN
            - name: pod-mounts
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/manila.csi.openstack.org
            type: DirectoryOrCreate
        - name: fwd-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/FWD-NODEPLUGIN
            type: Directory
        - name: pod-mounts
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
